### ISSUE TITLE
blaze dependency

### ISSUE THREAD

**Issue by nick-youngblut** [OliverVoogd/FLAMES#34]
The install README does not list [BLAZE](https://github.com/shimlab/BLAZE) as an (optional) dependency. 

More generally, the docs simply state:

```
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("FLAMES")
```

...but there are other system-level dependencies that will not be installed via the BiocManager. From the DESCRIPTION:

```
SystemRequirements: GNU make, C++17, samtools (>= 1.19), minimap2 (>= 2.17)
```

It would be helpful to list all system-level dependencies in the README install instructions, and how to install these system-level dependencies.

For example:

```
mamba create -n flames \
  python=3.10 "samtools>=1.14" "minimap2>=2.28" pysam numpy editdistance \
  blaze2 bioconductor-flames
```

... along with `pip3 install blaze2`, since there is no conda recipe for blaze. Given the lack of the recipe, one could use:

```yaml
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - numpy
  - pysam
  - editdistance
  - samtools>=1.14
  - minimap2>=2.28
  - bioconductor-flames
  - pip
  - pip:
      - blaze2
```

It would be helpful to know which versions of `numpy`, `pysam` and `editdistance` are supported.

I should note that installing flames via conda is **MUCH** faster than compiling all the C code for all R packages when using `BiocManager::install("FLAMES")`.

**Comment by nick-youngblut** [comment]
...but note that, currently, if one installs `bioconductor-flames` via conda/mamba (`bioconductor-flames 1.8.0`), then they will run into the error: `Could not locate k8 and[/or](http://localhost:9955/or) paftools.js in the minimap2 folder`, as described at https://github.com/mritchielab/FLAMES/issues/26.

So the install becomes:

```yaml
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - numpy
  - pysam
  - editdistance
  - samtools>=1.14
  - minimap2>=2.28
  - bioconductor-flames
  - r-remotes
  - pip
  - pip:
      - blaze2
```

```bash
mamba create -n flames --file flames_conda_env.yaml
```

```bash
git clone git clone https://github.com/mritchielab/FLAMES.git
```

Apply the patch from https://github.com/mritchielab/FLAMES/issues/26.

```bash
R -e "remotes::install_local('/path/to/cloned/and/patched/FLAMES', force = T, quiet = T,  upgrade = 'never')"
```
